### ISSUE TITLE
Injecting to 64-bit process

### ISSUE THREAD

**Issue by saykowa** [MicroCBer/EasyCEFInject#1]
Hi there! As i see, dll was not updated in a long time. So i just asking. Need to inject this dll to 64-bit process, trying to do this with Xenos. I am so bad at this, but as i understood, i need this dll in 64-bit format. I recompilied it, but nothing works. 

**Steps:**
1) Created easycefinject.js with one-code line: `alert('Injected')`
2) Placed `EasyCEFInject.dll` and `easycefinject.js` in same folder
3) Run Steam client, wait untill `steamwebhelper.exe` process with login window will be appeared
4) Putting `EasyCEFInject.dll` and `steamwebhelper.exe` process in Xenos, injecting
5) Trying to force `steamwebhelper.exe` window update (such as incorrect login credentials, QR update, etc.)

Trying to inject into `steamwebhelper.exe` which using CEF

**Comment by MicroCBer** [comment]
I have changed the code a lot, you can reference to https://github.com/MicroCBer/BetterNCM, which has done x64 support, for more information.

For steam, I actually suggest you to directly unpack and repack the resource files, as it seems that steam allows you to do so.

Don't be evil :)

**Comment by saykowa** [comment]
> you can reference to https://github.com/MicroCBer/BetterNCM, which has done x64 support, for more information

I saw that repo and i am dont mad, just feeling stupid myself. As i understood, BetterNCM is music library-like app, how do this contacting to dll injecting?

**Comment by MicroCBer** [comment]
The project is based on this project.

Btw, you might need to inject the dll in a pretty early stage, for the functions to work. Like, when the process is just started and cef is not initialized yet.
